### ISSUE TITLE
We need to make .chm for this script extension.

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#12]
Now we don't provide a help file for our extension. So It's hard to understand the correct usage way during script or test editing.

**Comment by terekhovm-pvt** [comment]
I don't think so. Putting binary chm on github is very bad idea. I think that there should be enough docs in Community forum thread for those people who want just download tcx and information in README.md on github for those people who are ready to inspect sources and propose their changes for the extension.
@AlexanderGubarev , what do you think.

**Comment by longmaxx** [comment]
We can use web URLs and open github page in case of Help call.
https://support.smartbear.com/testcomplete/docs/working-with/extending/script/creating/calling-help.html

**Comment by AlexanderGubarev** [comment]
KDT operation dialog was removed, script engine unable to invoke external Help on F1
So, it can be fixed properly because of restrictions of TestComplete

**Comment by AlexanderGubarev** [comment]
Actually, it's not good to have .chm file, because we contribute open-source "product" and it's hard to maintain .chm documentation, so, I agree with Max about .chm.

As fix of the problem with Help, I've changed HomePage link in Install Script Extension dialog, so, it follows to https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension (and will be changed after switching to new repo)
